<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lastbastion</groupId>
        <artifactId>last-bastion-server</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>app</artifactId>
    <name>app</name>

    <dependencies>
        <dependency>
            <groupId>com.lastbastion</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lastbastion</groupId>
            <artifactId>combat-engine</artifactId>
        </dependency>
        <dependency>
            <groupId>com.lastbastion</groupId>
            <artifactId>game-logic</artifactId>
        </dependency>
        <dependency>
            <groupId>com.iohao.game</groupId>
            <artifactId>run-one-netty</artifactId>
            <version>${iogame.version}</version>
        </dependency>
        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <finalName>last-bastion-app</finalName>
    </build>
</project>
